import "./globals.css";
import { NavLinks } from '@/components/nav-links';
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div style={{width: '1024px', maxWidth: '100vw', margin:'0 auto'}}>
        <NavLinks/>{children}
      </div>
      </body>
    </html>
  );
}
